export const START_LOGIN_GOOGLE = "START_LOGIN_GOOGLE";
export const END_LOGIN_GOOGLE = "END_LOGIN_GOOGLE";
export const START_LOGIN_MAIL = "START_LOGIN_MAIL";
export const END_LOGIN_MAIL = "END_LOGIN_MAIL";
export const START_SIGNUP_GOOGLE = "START_SIGNUP_GOOGLE";
export const END_SIGNUP_GOOGLE = "END_SIGNUP_GOOGLE";
export const START_SIGNUP_MAIL = "START_SIGNUP_MAIL";
export const END_SIGNUP_MAIL = "END_SIGNUP_MAIL";


export const START_AUTH = "START_LOGIN";
export const END_AUTH = "END_LOGIN";